/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TechQuizApp.gui;

import TechQuizApp.dao.QuestionListDao;
import TechQuizApp.pojo.ArrayListClass;
import TechQuizApp.pojo.ExamDetailsPojo;
import TechQuizApp.pojo.QuestionsDetailPojo;
import TechQuizApp.pojo.UserProfile;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Set;
import javax.swing.JOptionPane;

/**
 *
 * @author india
 */
public class EditQuestionsFrame extends javax.swing.JFrame {
    private Color old;
    private ExamDetailsPojo edp;
    private ArrayList<QuestionsDetailPojo> al;
    private int ques;
    private int pos;
    private ArrayListClass alc;
    private HashMap<String , String> hs;
    private String question;
    private String option1;
    private String option2;
    private String option3;
    private String option4;
    private String answer;

    /**
     * Creates new form SetQuestionFrame
     */
    public EditQuestionsFrame() {
        initComponents();
        this.setTitle("TECHQUIZ APP");
        jtfUserName.setText("HELLO "+UserProfile.getUserNameInProfile().toUpperCase());
        ques=1;
        pos=0;
        alc = new ArrayListClass();
        jlblQuestionNumber.setText("QUESTION NUMBER :- "+ques);
        hs = new HashMap<>();
         hs.put("Option-1", "Answer-1");
         hs.put("Option-2", "Answer-2");
          hs.put("Option-3", "Answer-3");
           hs.put("Option-4", "Answer-4");
           old = jlblLogout.getForeground();
           this.setLocationRelativeTo(null);
        
       
    }
    public EditQuestionsFrame(ExamDetailsPojo edp)
    {
        this();
        this.edp = edp;
        loadQuestions();
         showQuestions();
            
         
    }
    private void showQuestions()
    {
        System.out.println("show questions called");
        QuestionsDetailPojo qdp = alc.get(pos);
       
        jtaQuestion.setText(qdp.getQuestion());
        System.out.println(qdp.getQuestion());
            jtfOption1.setText(qdp.getOption1());
            jtfOption2.setText(qdp.getOption2());
            jtfOption3.setText(qdp.getOption3());
            System.out.println(qdp.getOption3());
            jtfOption4.setText(qdp.getOption4());
            String str = qdp.getAnswer();
            String str1 = getKeyFromValue(str);
            jcbCorrectAnswer.setSelectedItem(str1);
        
    }
    private String getKeyFromValue(String value)
    {
        Set<String > keys= hs.keySet();
        for(String str :keys)
        {
            if(hs.get(str).equalsIgnoreCase(value))
                return str;
        }
        return null;
    }
private void loadQuestions()
{
   try
   {
       al = QuestionListDao.getAllQuestionsFromExamId(edp.getExamId());
        if(al.isEmpty())
            {
                JOptionPane.showMessageDialog(null, "NO QUESTIONS AVAILABLE" , "ERROR" , JOptionPane.ERROR_MESSAGE);
                return;
            }
        for(QuestionsDetailPojo x: al)
        {
            System.out.println("loop iterated");
            alc.add(x);
        }
   }
   catch(SQLException sq)
         {
             JOptionPane.showMessageDialog(null, "PROBLEM WITH THE DATABASE" , "ERROR" , JOptionPane.ERROR_MESSAGE);
             sq.printStackTrace();
         }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaQuestion = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfOption1 = new javax.swing.JTextField();
        jtfOption2 = new javax.swing.JTextField();
        jtfOption3 = new javax.swing.JTextField();
        jtfOption4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jlblQuestionNumber = new javax.swing.JLabel();
        jcbCorrectAnswer = new javax.swing.JComboBox();
        jlblLogout = new javax.swing.JLabel();
        jtfUserName = new javax.swing.JLabel();
        jbtnNext = new javax.swing.JButton();
        jbtnPrevious = new javax.swing.JButton();
        jbtnDone = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 114, 146));
        jPanel1.setPreferredSize(new java.awt.Dimension(808, 472));

        jtaQuestion.setColumns(20);
        jtaQuestion.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jtaQuestion.setRows(5);
        jScrollPane1.setViewportView(jtaQuestion);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Option-1");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Option-2");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Option-3");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Option-4");

        jtfOption1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        jtfOption2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        jtfOption3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        jtfOption4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Correct Answer");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TechQuizApp/gui/questionpaper.jpg"))); // NOI18N

        jlblQuestionNumber.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblQuestionNumber.setForeground(new java.awt.Color(255, 255, 255));

        jcbCorrectAnswer.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jcbCorrectAnswer.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Option-1", "Option-2", "Option-3", "Option-4" }));

        jlblLogout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblLogout.setForeground(new java.awt.Color(255, 255, 255));
        jlblLogout.setText("Logout");
        jlblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlblLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlblLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlblLogoutMouseExited(evt);
            }
        });

        jtfUserName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtfUserName.setForeground(new java.awt.Color(255, 255, 255));

        jbtnNext.setBackground(new java.awt.Color(0, 0, 0));
        jbtnNext.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnNext.setForeground(new java.awt.Color(255, 255, 255));
        jbtnNext.setText("Next");
        jbtnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNextActionPerformed(evt);
            }
        });

        jbtnPrevious.setBackground(new java.awt.Color(0, 0, 0));
        jbtnPrevious.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnPrevious.setForeground(new java.awt.Color(255, 255, 255));
        jbtnPrevious.setText("Previous");
        jbtnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPreviousActionPerformed(evt);
            }
        });

        jbtnDone.setBackground(new java.awt.Color(0, 0, 0));
        jbtnDone.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnDone.setForeground(new java.awt.Color(255, 255, 255));
        jbtnDone.setText("Done");
        jbtnDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtfOption3, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .addComponent(jtfOption2)
                    .addComponent(jtfOption4)
                    .addComponent(jtfOption1)
                    .addComponent(jcbCorrectAnswer, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(97, 97, 97)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnPrevious)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jbtnNext, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnDone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)))
                .addGap(72, 72, 72))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jlblQuestionNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtfUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlblLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlblLogout)
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jtfOption1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnNext))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtfOption2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtfOption3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jbtnDone))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfOption4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jlblQuestionNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jcbCorrectAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnPrevious)
                                .addGap(7, 7, 7))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtfUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNextActionPerformed
        if(!validateInputs())
        {
            JOptionPane.showMessageDialog(null, "PLEASE FILL ALL THE FIELDS FIRST" , "ERROR" , JOptionPane.ERROR_MESSAGE);
            return;
        }
        QuestionsDetailPojo qdp = new QuestionsDetailPojo();
        qdp.setExamId(edp.getExamId());
        qdp.setQnunmber(ques);
        qdp.setSubject(edp.getExamSubject());
        qdp.setQuestion(question);
        qdp.setOption1(option1);
        qdp.setOption2(option2);
        qdp.setOption3(option3);
        qdp.setOption4(option4);
        qdp.setAnswer(answer);
        alc.removeElement(pos);
        alc.setQuestionAt(qdp, pos);
        pos++;
        if(pos>=alc.getCount())
        {
         JOptionPane.showMessageDialog(null, "YOU HAVE EDITED ALL THE QUESTIONS" , "COMPLETE" , JOptionPane.INFORMATION_MESSAGE);
            pos=0;
        }
        showQuestions();
        ques++;
        if(ques>alc.getCount())
        {
            ques=1;
        }
        jlblQuestionNumber.setText("QUESTION NUMBER :- "+ques);
        
    }//GEN-LAST:event_jbtnNextActionPerformed

    private void jbtnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPreviousActionPerformed
        if(!validateInputs())
        {
            JOptionPane.showMessageDialog(null, "PLEASE FILL ALL THE FIELDS FIRST" , "ERROR" , JOptionPane.ERROR_MESSAGE);
            return;
        }
        QuestionsDetailPojo qdp = new QuestionsDetailPojo();
        qdp.setAnswer(answer);
        qdp.setExamId(edp.getExamId());
        qdp.setOption1(option1);
        qdp.setOption2(option2);
        qdp.setOption3(option3);
        qdp.setOption4(option4);
        qdp.setSubject(qdp.getSubject());
        qdp.setQuestion(question);
        qdp.setQnunmber(ques);
        alc.removeElement(pos);
        alc.setQuestionAt(qdp, pos);
        pos--;
        if(pos<0)
        {
            JOptionPane.showMessageDialog(null, "YOU HAVE EDITED ALL THE QUESTIONS" , "COMPLETE" , JOptionPane.INFORMATION_MESSAGE);
            pos = alc.getCount()-1;
        }
        showQuestions();
        ques--;
        if(ques<=0)
        {
            ques = alc.getCount();
        }
        jlblQuestionNumber.setText("QUESTION NUMBER :- "+ques);
        
    }//GEN-LAST:event_jbtnPreviousActionPerformed

    private void jbtnDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDoneActionPerformed
        try
        {
            QuestionListDao.fillAllQuestionsAgain(alc);
            JOptionPane.showMessageDialog(null , "PAPER EDITED SUCCESSFULLY" , "COMPLETED" , JOptionPane.INFORMATION_MESSAGE);
            AdminOptionFrame aof = new AdminOptionFrame();
            aof.setVisible(true);
            this.dispose();
        }
        catch(SQLException sq)
        {
            JOptionPane.showMessageDialog(null, "PROBLEM WITH THE DATABASE" , "ERROR" , JOptionPane.ERROR_MESSAGE);
            sq.printStackTrace();
        }
    }//GEN-LAST:event_jbtnDoneActionPerformed

    private void jlblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblLogoutMouseClicked
        LoginFrame lf= new LoginFrame();
        lf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jlblLogoutMouseClicked

    private void jlblLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblLogoutMouseEntered
            jlblLogout.setForeground(Color.red);
    }//GEN-LAST:event_jlblLogoutMouseEntered

    private void jlblLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblLogoutMouseExited
        jlblLogout.setForeground(old);
    }//GEN-LAST:event_jlblLogoutMouseExited
    private boolean validateInputs()
    {
        question = jtaQuestion.getText().trim();
        option1 = jtfOption1.getText().trim();
        option2 = jtfOption2.getText().trim();
        option3 = jtfOption3.getText().trim();
        option4 = jtfOption4.getText().trim();
        answer = hs.get(jcbCorrectAnswer.getSelectedItem()).trim();
        if(question.isEmpty()||option1.isEmpty()||option2.isEmpty()||option3.isEmpty()||option4.isEmpty()||answer.isEmpty())
        {
            return false;
        }
        return true;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditQuestionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditQuestionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditQuestionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditQuestionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditQuestionsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnDone;
    private javax.swing.JButton jbtnNext;
    private javax.swing.JButton jbtnPrevious;
    private javax.swing.JComboBox jcbCorrectAnswer;
    private javax.swing.JLabel jlblLogout;
    private javax.swing.JLabel jlblQuestionNumber;
    private javax.swing.JTextArea jtaQuestion;
    private javax.swing.JTextField jtfOption1;
    private javax.swing.JTextField jtfOption2;
    private javax.swing.JTextField jtfOption3;
    private javax.swing.JTextField jtfOption4;
    private javax.swing.JLabel jtfUserName;
    // End of variables declaration//GEN-END:variables
}
